export const SEARCH_FRIEND_REQUEST = 'SSEARCH_FRIEND_REQUEST';
export const SEARCH_FRIEND_RESPONSE = 'SSEARCH_FRIEND_RESPONSE';
export const GET_LIST_FRIEND_REQUEST = 'GET_LIST_FRIEND_REQUEST';
export const GET_LIST_FRIEND_RESPONSE = 'GET_LIST_FRIEND_RESPONSE';
export const SEND_ADD_FRIEND_REQUEST = 'SEND_ADD_FRIEND_REQUEST';
export const SEND_ADD_FRIEND_RESPONSE = 'SEND_ADD_FRIEND_RESPONSE';

export const GET_LIST_FRIEND_REQUEST_REQUEST = 'GET_LIST_FRIEND_REQUEST_REQUEST';
export const GET_LIST_FRIEND_REQUEST_RESPONSE = 'GET_LIST_FRIEND_REQUEST_RESPONSE';

export const ACCEPT_FRIEND_REQUEST_REQUEST = 'ACCEPT_FRIEND_REQUEST_REQUEST';
export const DECLINE_FRIEND_REQUEST_REQUEST = 'DECLINE_FRIEND_REQUEST_REQUEST';  


export const CLOSE_MODAL = 'CLOSE_MODAL';