export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const OPEN_NEXT_MODAL = 'OPEN_NEXT_MODAL';
export const OPEN_PREV_MODAL = 'OPEN_PREV_MODAL';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';