export const CREATE_ROOM_REQUEST = 'CREATE_ROOM_REQUEST';
export const JOIN_ROOM_REQUEST = 'JOIN_ROOM_REQUEST';
export const UPDATE_ROOM_DATA = 'UPDATE_ROOM_DATA'; 

export const LEAVE_ROOM_REQUEST = 'LEAVE_ROOM_REQUEST';
export const LEAVE_ROOM_RESPONSE = 'LEAVE_ROOM_RESPONSE';

export const SEND_MESSAGE = 'SEND_MESSAGE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';