export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_RESPONSE = 'GET_USER_RESPONSE'; 
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_FULLNAME_REQUEST = 'CHANGE_FULLNAME_REQUEST';
export const CHANGE_AVATA_REQUEST = 'CHANGE_AVATA_REQUEST';