 module.exports = {
    IS_LOGIN : 'IS_LOGIN',
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_ERROR : 'LOGIN_ERROR',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    SIGN_UP_REQUEST : 'SIGN_UP_REQUEST',
    SIGN_UP_RESPONE : 'SIGN_UP_RESPONSE',
    SIGNUP_ERROR : 'SIGNUP_ERROR'
 }
